language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5

before_install:
  - npm install --global npm@latest

install:
  - npm install
  - pushd example && npm install && popd

script:
  - node --version && npm --version
  - npm run test-coverage
  - pushd example && node build.js && popd

after_success:
  - npm run codeclimate

###

sudo: false

addons:
  code_climate:
    repo_token:
      secure: SmzRS/9BnajgeebIYSgB6g/EoyKWLNuuLROQULjjCR2BOqSL+TyngZb06yl0YQXcSTOStC2z/CtEttuORGB6iZ/Vp5Oo2qVcKRm2CAB4JVUGpi/EWPsMWfGRNQ6qXWVEluqEynme6lvK2mZTdqRFvE9Hvx4rXbLLOWy36LZXP0Y=
