environment:
  - node_js: 4
  - node_js: 5
  - node_js: 6
  - node_js: 7

install:
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

###

build: off

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> yarn.lock
  - example/node_modules -> yarn.lock

clone_depth: 1

init:
  - ps: Install-Product node $env:node_js
  - choco install yarn
  - refreshenv

matrix:
  fast_finish: true

shallow_clone: true

version: '#{build}'
